spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3307/test?useSSL=false&characterEncoding=UTF-8&serverTimezone=JST
    username: root
    password: root
    type: com.zaxxer.hikari.HikariDataSource
    hikari:
      minimum-idle: 5
      maximum-pool-size: 20
      auto-commit: true
      idle-timeout: 30000
      pool-name: WSHikariCP
      max-lifetime: 1800000
      connection-timeout: 30000
      connection-test-query: SELECT 1
  redis:
    database: 0
    host: 193.160.26.21
    port: 6379
    password: Fnst.1234
    jedis:
      pool:
        max-active: 8
        max-wait: -1
        max-idle: 5
        min-idle: 0
#    lettuce:
#      pool:
#        max-active: 8
#        max-wait: -1
#        max-idle: 8
#        min-idle: 0
    timeout: 1000
  application:
    name: testBoot
    version: 1.0

server:
  port: 9090

vehicle:
  api: 
    vehicle-string-url: http://127.0.0.1:8082/testapi/getString

mybatis:
  mapper-locations: classpath*:/mapper/*.xml
  type-aliases-package: com.gedc.entity
  configLocation: classpath:mybatis-config.xml
  